const nodes = [];

nodes.push({id: "Abomination", image: "https://images.marvelsnap.io/images/cards/1.webp", shape: "image"});
nodes.push({id: "Absorbing Man", image: "https://images.marvelsnap.io/images/cards/200.webp", shape: "image"});
nodes.push({id: "Adam Warlock", image: "https://images.marvelsnap.io/images/cards/201.webp", shape: "image"});
nodes.push({id: "Aero", image: "https://images.marvelsnap.io/images/cards/2.webp", shape: "image"});
nodes.push({id: "Agatha Harkness", image: "https://images.marvelsnap.io/images/cards/202.webp", shape: "image"});
nodes.push({id: "Agent 13", image: "https://images.marvelsnap.io/images/cards/3.webp", shape: "image"});
nodes.push({id: "Agent Coulson", image: "https://images.marvelsnap.io/images/cards/203.webp", shape: "image"});
nodes.push({id: "America Chavez", image: "https://images.marvelsnap.io/images/cards/4.webp", shape: "image"});
nodes.push({id: "Angel", image: "https://images.marvelsnap.io/images/cards/5.webp", shape: "image"});
nodes.push({id: "Angela", image: "https://images.marvelsnap.io/images/cards/6.webp", shape: "image"});
nodes.push({id: "Ant-Man", image: "https://images.marvelsnap.io/images/cards/7.webp", shape: "image"});
nodes.push({id: "Apocalypse", image: "https://images.marvelsnap.io/images/cards/8.webp", shape: "image"});
nodes.push({id: "Armor", image: "https://images.marvelsnap.io/images/cards/9.webp", shape: "image"});
nodes.push({id: "Arnim Zola", image: "https://images.marvelsnap.io/images/cards/10.webp", shape: "image"});
nodes.push({id: "Attuma", image: "https://images.marvelsnap.io/images/cards/340.webp", shape: "image"});
nodes.push({id: "Baron Mordo", image: "https://images.marvelsnap.io/images/cards/11.webp", shape: "image"});
nodes.push({id: "Bast", image: "https://images.marvelsnap.io/images/cards/341.webp", shape: "image"});
nodes.push({id: "Beast", image: "https://images.marvelsnap.io/images/cards/12.webp", shape: "image"});
nodes.push({id: "Bishop", image: "https://images.marvelsnap.io/images/cards/13.webp", shape: "image"});
nodes.push({id: "Black Bolt", image: "https://images.marvelsnap.io/images/cards/14.webp", shape: "image"});
nodes.push({id: "Black Cat", image: "https://images.marvelsnap.io/images/cards/15.webp", shape: "image"});
nodes.push({id: "Black Knight", image: "https://images.marvelsnap.io/images/cards/204.webp", shape: "image"});
nodes.push({id: "Black Panther", image: "https://images.marvelsnap.io/images/cards/16.webp", shape: "image"});
nodes.push({id: "Black Widow", image: "https://images.marvelsnap.io/images/cards/17.webp", shape: "image"});
nodes.push({id: "Blade", image: "https://images.marvelsnap.io/images/cards/18.webp", shape: "image"});
nodes.push({id: "Blink", image: "https://images.marvelsnap.io/images/cards/205.webp", shape: "image"});
nodes.push({id: "Blob", image: "https://images.marvelsnap.io/images/cards/206.webp", shape: "image"});
nodes.push({id: "Blue Marvel", image: "https://images.marvelsnap.io/images/cards/19.webp", shape: "image"});
nodes.push({id: "Brood", image: "https://images.marvelsnap.io/images/cards/20.webp", shape: "image"});
nodes.push({id: "Bucky Barnes", image: "https://images.marvelsnap.io/images/cards/207.webp", shape: "image"});
nodes.push({id: "Bullseye", image: "https://images.marvelsnap.io/images/cards/208.webp", shape: "image"});
nodes.push({id: "Cable", image: "https://images.marvelsnap.io/images/cards/21.webp", shape: "image"});
nodes.push({id: "Captain America", image: "https://images.marvelsnap.io/images/cards/22.webp", shape: "image"});
nodes.push({id: "Captain Marvel", image: "https://images.marvelsnap.io/images/cards/23.webp", shape: "image"});
nodes.push({id: "Carnage", image: "https://images.marvelsnap.io/images/cards/24.webp", shape: "image"});
nodes.push({id: "Cerebro", image: "https://images.marvelsnap.io/images/cards/25.webp", shape: "image"});
nodes.push({id: "Cloak", image: "https://images.marvelsnap.io/images/cards/26.webp", shape: "image"});
nodes.push({id: "Colleen Wing", image: "https://images.marvelsnap.io/images/cards/209.webp", shape: "image"});
nodes.push({id: "Colossus", image: "https://images.marvelsnap.io/images/cards/27.webp", shape: "image"});
nodes.push({id: "Cosmo", image: "https://images.marvelsnap.io/images/cards/28.webp", shape: "image"});
nodes.push({id: "Crossbones", image: "https://images.marvelsnap.io/images/cards/210.webp", shape: "image"});
nodes.push({id: "Crystal", image: "https://images.marvelsnap.io/images/cards/29.webp", shape: "image"});
nodes.push({id: "Cyclops", image: "https://images.marvelsnap.io/images/cards/30.webp", shape: "image"});
nodes.push({id: "Dagger", image: "https://images.marvelsnap.io/images/cards/31.webp", shape: "image"});
nodes.push({id: "Daredevil", image: "https://images.marvelsnap.io/images/cards/211.webp", shape: "image"});
nodes.push({id: "Darkhawk", image: "https://images.marvelsnap.io/images/cards/212.webp", shape: "image"});
nodes.push({id: "Dazzler", image: "https://images.marvelsnap.io/images/cards/213.webp", shape: "image"});
nodes.push({id: "Deadpool", image: "https://images.marvelsnap.io/images/cards/32.webp", shape: "image"});
nodes.push({id: "Death", image: "https://images.marvelsnap.io/images/cards/33.webp", shape: "image"});
nodes.push({id: "Deathlok", image: "https://images.marvelsnap.io/images/cards/34.webp", shape: "image"});
nodes.push({id: "Debrii", image: "https://images.marvelsnap.io/images/cards/214.webp", shape: "image"});
nodes.push({id: "Destroyer", image: "https://images.marvelsnap.io/images/cards/35.webp", shape: "image"});
nodes.push({id: "Devil Dinosaur", image: "https://images.marvelsnap.io/images/cards/36.webp", shape: "image"});
nodes.push({id: "Doctor Doom", image: "https://images.marvelsnap.io/images/cards/37.webp", shape: "image"});
nodes.push({id: "Doctor Octopus", image: "https://images.marvelsnap.io/images/cards/38.webp", shape: "image"});
nodes.push({id: "Doctor Strange", image: "https://images.marvelsnap.io/images/cards/39.webp", shape: "image"});
nodes.push({id: "Domino", image: "https://images.marvelsnap.io/images/cards/40.webp", shape: "image"});
nodes.push({id: "Dracula", image: "https://images.marvelsnap.io/images/cards/215.webp", shape: "image"});
nodes.push({id: "Drax", image: "https://images.marvelsnap.io/images/cards/41.webp", shape: "image"});
nodes.push({id: "Ebony Maw", image: "https://images.marvelsnap.io/images/cards/42.webp", shape: "image"});
nodes.push({id: "Electro", image: "https://images.marvelsnap.io/images/cards/43.webp", shape: "image"});
nodes.push({id: "Elektra", image: "https://images.marvelsnap.io/images/cards/44.webp", shape: "image"});
nodes.push({id: "Elsa Bloodstone", image: "https://images.marvelsnap.io/images/cards/216.webp", shape: "image"});
nodes.push({id: "Enchantress", image: "https://images.marvelsnap.io/images/cards/217.webp", shape: "image"});
nodes.push({id: "Falcon", image: "https://images.marvelsnap.io/images/cards/218.webp", shape: "image"});
nodes.push({id: "Forge", image: "https://images.marvelsnap.io/images/cards/45.webp", shape: "image"});
nodes.push({id: "Galactus", image: "https://images.marvelsnap.io/images/cards/46.webp", shape: "image"});
nodes.push({id: "Gambit", image: "https://images.marvelsnap.io/images/cards/47.webp", shape: "image"});
nodes.push({id: "Gamora", image: "https://images.marvelsnap.io/images/cards/48.webp", shape: "image"});
nodes.push({id: "Ghost Rider", image: "https://images.marvelsnap.io/images/cards/49.webp", shape: "image"});
nodes.push({id: "Ghost-Spider", image: "https://images.marvelsnap.io/images/cards/263.webp", shape: "image"});
nodes.push({id: "Giganto", image: "https://images.marvelsnap.io/images/cards/219.webp", shape: "image"});
nodes.push({id: "Goose", image: "https://images.marvelsnap.io/images/cards/50.webp", shape: "image"});
nodes.push({id: "Green Goblin", image: "https://images.marvelsnap.io/images/cards/51.webp", shape: "image"});
nodes.push({id: "Groot", image: "https://images.marvelsnap.io/images/cards/52.webp", shape: "image"});
nodes.push({id: "Hawkeye", image: "https://images.marvelsnap.io/images/cards/53.webp", shape: "image"});
nodes.push({id: "Hazmat", image: "https://images.marvelsnap.io/images/cards/54.webp", shape: "image"});
nodes.push({id: "Heimdall", image: "https://images.marvelsnap.io/images/cards/55.webp", shape: "image"});
nodes.push({id: "Hela", image: "https://images.marvelsnap.io/images/cards/305.webp", shape: "image"});
nodes.push({id: "Helicarrier", image: "https://images.marvelsnap.io/images/cards/342.webp", shape: "image"});
nodes.push({id: "Hellcow", image: "https://images.marvelsnap.io/images/cards/56.webp", shape: "image"});
nodes.push({id: "Hit Monkey", image: "https://images.marvelsnap.io/images/cards/220.webp", shape: "image"});
nodes.push({id: "Hobgoblin", image: "https://images.marvelsnap.io/images/cards/57.webp", shape: "image"});
nodes.push({id: "Hulk", image: "https://images.marvelsnap.io/images/cards/58.webp", shape: "image"});
nodes.push({id: "Hulk Buster", image: "https://images.marvelsnap.io/images/cards/221.webp", shape: "image"});
nodes.push({id: "Human Torch", image: "https://images.marvelsnap.io/images/cards/59.webp", shape: "image"});
nodes.push({id: "Iceman", image: "https://images.marvelsnap.io/images/cards/60.webp", shape: "image"});
nodes.push({id: "Invisible Woman", image: "https://images.marvelsnap.io/images/cards/61.webp", shape: "image"});
nodes.push({id: "Iron Fist", image: "https://images.marvelsnap.io/images/cards/62.webp", shape: "image"});
nodes.push({id: "Iron Man", image: "https://images.marvelsnap.io/images/cards/63.webp", shape: "image"});
nodes.push({id: "Ironheart", image: "https://images.marvelsnap.io/images/cards/64.webp", shape: "image"});
nodes.push({id: "Jane Foster Mighty Thor", image: "https://images.marvelsnap.io/images/cards/300.webp", shape: "image"});
nodes.push({id: "Jean Grey", image: "https://images.marvelsnap.io/images/cards/222.webp", shape: "image"});
nodes.push({id: "Jessica Jones", image: "https://images.marvelsnap.io/images/cards/65.webp", shape: "image"});
nodes.push({id: "Jubilee", image: "https://images.marvelsnap.io/images/cards/66.webp", shape: "image"});
nodes.push({id: "Juggernaut", image: "https://images.marvelsnap.io/images/cards/223.webp", shape: "image"});
nodes.push({id: "Kang", image: "https://images.marvelsnap.io/images/cards/67.webp", shape: "image"});
nodes.push({id: "Kazar", image: "https://images.marvelsnap.io/images/cards/68.webp", shape: "image"});
nodes.push({id: "Killmonger", image: "https://images.marvelsnap.io/images/cards/69.webp", shape: "image"});
nodes.push({id: "Kingpin", image: "https://images.marvelsnap.io/images/cards/70.webp", shape: "image"});
nodes.push({id: "Kitty Pryde", image: "https://images.marvelsnap.io/images/cards/224.webp", shape: "image"});
nodes.push({id: "Klaw", image: "https://images.marvelsnap.io/images/cards/71.webp", shape: "image"});
nodes.push({id: "Knull", image: "https://images.marvelsnap.io/images/cards/343.webp", shape: "image"});
nodes.push({id: "Korg", image: "https://images.marvelsnap.io/images/cards/225.webp", shape: "image"});
nodes.push({id: "Kraven", image: "https://images.marvelsnap.io/images/cards/72.webp", shape: "image"});
nodes.push({id: "Lady Deathstrike", image: "https://images.marvelsnap.io/images/cards/226.webp", shape: "image"});
nodes.push({id: "Lady Sif", image: "https://images.marvelsnap.io/images/cards/73.webp", shape: "image"});
nodes.push({id: "Leader", image: "https://images.marvelsnap.io/images/cards/227.webp", shape: "image"});
nodes.push({id: "Leech", image: "https://images.marvelsnap.io/images/cards/74.webp", shape: "image"});
nodes.push({id: "Legion", image: "https://images.marvelsnap.io/images/cards/228.webp", shape: "image"});
nodes.push({id: "Lizard", image: "https://images.marvelsnap.io/images/cards/75.webp", shape: "image"});
nodes.push({id: "Lockjaw", image: "https://images.marvelsnap.io/images/cards/229.webp", shape: "image"});
nodes.push({id: "Loki", image: "https://images.marvelsnap.io/images/cards/230.webp", shape: "image"});
nodes.push({id: "Luke Cage", image: "https://images.marvelsnap.io/images/cards/231.webp", shape: "image"});
nodes.push({id: "M'Baku", image: "https://images.marvelsnap.io/images/cards/232.webp", shape: "image"});
nodes.push({id: "Magik", image: "https://images.marvelsnap.io/images/cards/76.webp", shape: "image"});
nodes.push({id: "Magneto", image: "https://images.marvelsnap.io/images/cards/77.webp", shape: "image"});
nodes.push({id: "Makkari", image: "https://images.marvelsnap.io/images/cards/233.webp", shape: "image"});
nodes.push({id: "Mantis", image: "https://images.marvelsnap.io/images/cards/78.webp", shape: "image"});
nodes.push({id: "Maria Hill", image: "https://images.marvelsnap.io/images/cards/234.webp", shape: "image"});
nodes.push({id: "Maximus", image: "https://images.marvelsnap.io/images/cards/79.webp", shape: "image"});
nodes.push({id: "Medusa", image: "https://images.marvelsnap.io/images/cards/80.webp", shape: "image"});
nodes.push({id: "Mephisto", image: "https://images.marvelsnap.io/images/cards/235.webp", shape: "image"});
nodes.push({id: "Mirage", image: "https://images.marvelsnap.io/images/cards/319.webp", shape: "image"});
nodes.push({id: "Mister Fantastic", image: "https://images.marvelsnap.io/images/cards/81.webp", shape: "image"});
nodes.push({id: "Mister Negative", image: "https://images.marvelsnap.io/images/cards/236.webp", shape: "image"});
nodes.push({id: "Mister Sinister", image: "https://images.marvelsnap.io/images/cards/82.webp", shape: "image"});
nodes.push({id: "Misty Knight", image: "https://images.marvelsnap.io/images/cards/237.webp", shape: "image"});
nodes.push({id: "MODOK", image: "https://images.marvelsnap.io/images/cards/238.webp", shape: "image"});
nodes.push({id: "Mojo", image: "https://images.marvelsnap.io/images/cards/83.webp", shape: "image"});
nodes.push({id: "Moon Girl", image: "https://images.marvelsnap.io/images/cards/84.webp", shape: "image"});
nodes.push({id: "Moon Knight", image: "https://images.marvelsnap.io/images/cards/239.webp", shape: "image"});
nodes.push({id: "Morbius", image: "https://images.marvelsnap.io/images/cards/240.webp", shape: "image"});
nodes.push({id: "Morph", image: "https://images.marvelsnap.io/images/cards/85.webp", shape: "image"});
nodes.push({id: "Ms Marvel", image: "https://images.marvelsnap.io/images/cards/241.webp", shape: "image"});
nodes.push({id: "Multiple Man", image: "https://images.marvelsnap.io/images/cards/86.webp", shape: "image"});
nodes.push({id: "Mysterio", image: "https://images.marvelsnap.io/images/cards/87.webp", shape: "image"});
nodes.push({id: "Mystique", image: "https://images.marvelsnap.io/images/cards/88.webp", shape: "image"});
nodes.push({id: "Nakia", image: "https://images.marvelsnap.io/images/cards/89.webp", shape: "image"});
nodes.push({id: "Namor", image: "https://images.marvelsnap.io/images/cards/90.webp", shape: "image"});
nodes.push({id: "Nebula", image: "https://images.marvelsnap.io/images/cards/242.webp", shape: "image"});
nodes.push({id: "Negasonic Teenage Warhead", image: "https://images.marvelsnap.io/images/cards/243.webp", shape: "image"});
nodes.push({id: "Nick Fury", image: "https://images.marvelsnap.io/images/cards/320.webp", shape: "image"});
nodes.push({id: "Nightcrawler", image: "https://images.marvelsnap.io/images/cards/91.webp", shape: "image"});
nodes.push({id: "Nova", image: "https://images.marvelsnap.io/images/cards/92.webp", shape: "image"});
nodes.push({id: "Odin", image: "https://images.marvelsnap.io/images/cards/93.webp", shape: "image"});
nodes.push({id: "Okoye", image: "https://images.marvelsnap.io/images/cards/94.webp", shape: "image"});
nodes.push({id: "Omega Red", image: "https://images.marvelsnap.io/images/cards/313.webp", shape: "image"});
nodes.push({id: "Onslaught", image: "https://images.marvelsnap.io/images/cards/95.webp", shape: "image"});
nodes.push({id: "Orka", image: "https://images.marvelsnap.io/images/cards/244.webp", shape: "image"});
nodes.push({id: "Patriot", image: "https://images.marvelsnap.io/images/cards/245.webp", shape: "image"});
nodes.push({id: "Phoenix Force", image: "https://images.marvelsnap.io/images/cards/246.webp", shape: "image"});
nodes.push({id: "Polaris", image: "https://images.marvelsnap.io/images/cards/96.webp", shape: "image"});
nodes.push({id: "Professor X", image: "https://images.marvelsnap.io/images/cards/97.webp", shape: "image"});
nodes.push({id: "Psylocke", image: "https://images.marvelsnap.io/images/cards/98.webp", shape: "image"});
nodes.push({id: "Quake", image: "https://images.marvelsnap.io/images/cards/100.webp", shape: "image"});
nodes.push({id: "Quicksilver", image: "https://images.marvelsnap.io/images/cards/101.webp", shape: "image"});
nodes.push({id: "Quinjet", image: "https://images.marvelsnap.io/images/cards/314.webp", shape: "image"});
nodes.push({id: "Red Guardian", image: "https://images.marvelsnap.io/images/cards/248.webp", shape: "image"});
nodes.push({id: "Red Skull", image: "https://images.marvelsnap.io/images/cards/102.webp", shape: "image"});
nodes.push({id: "Rescue", image: "https://images.marvelsnap.io/images/cards/103.webp", shape: "image"});
nodes.push({id: "Rhino", image: "https://images.marvelsnap.io/images/cards/104.webp", shape: "image"});
nodes.push({id: "Rocket Racoon", image: "https://images.marvelsnap.io/images/cards/105.webp", shape: "image"});
nodes.push({id: "Rockslide", image: "https://images.marvelsnap.io/images/cards/106.webp", shape: "image"});
nodes.push({id: "Rogue", image: "https://images.marvelsnap.io/images/cards/107.webp", shape: "image"});
nodes.push({id: "Ronan the Accuser", image: "https://images.marvelsnap.io/images/cards/250.webp", shape: "image"});
nodes.push({id: "Sabretooth", image: "https://images.marvelsnap.io/images/cards/251.webp", shape: "image"});
nodes.push({id: "Sandman", image: "https://images.marvelsnap.io/images/cards/108.webp", shape: "image"});
nodes.push({id: "Sauron", image: "https://images.marvelsnap.io/images/cards/345.webp", shape: "image"});
nodes.push({id: "Scarlet Witch", image: "https://images.marvelsnap.io/images/cards/109.webp", shape: "image"});
nodes.push({id: "Scorpion", image: "https://images.marvelsnap.io/images/cards/110.webp", shape: "image"});
nodes.push({id: "Sentinel", image: "https://images.marvelsnap.io/images/cards/111.webp", shape: "image"});
nodes.push({id: "Sentry", image: "https://images.marvelsnap.io/images/cards/252.webp", shape: "image"});
nodes.push({id: "Sera", image: "https://images.marvelsnap.io/images/cards/112.webp", shape: "image"});
nodes.push({id: "Shadow King", image: "https://images.marvelsnap.io/images/cards/253.webp", shape: "image"});
nodes.push({id: "Shang-Chi", image: "https://images.marvelsnap.io/images/cards/113.webp", shape: "image"});
nodes.push({id: "Shanna the She-Devil", image: "https://images.marvelsnap.io/images/cards/254.webp", shape: "image"});
nodes.push({id: "She-Hulk", image: "https://images.marvelsnap.io/images/cards/255.webp", shape: "image"});
nodes.push({id: "Shocker", image: "https://images.marvelsnap.io/images/cards/114.webp", shape: "image"});
nodes.push({id: "Shuri", image: "https://images.marvelsnap.io/images/cards/256.webp", shape: "image"});
nodes.push({id: "Silk", image: "https://images.marvelsnap.io/images/cards/257.webp", shape: "image"});
nodes.push({id: "Silver Sable", image: "https://images.marvelsnap.io/images/cards/258.webp", shape: "image"});
nodes.push({id: "Silver Samurai", image: "https://images.marvelsnap.io/images/cards/259.webp", shape: "image"});
nodes.push({id: "Silver Surfer", image: "https://images.marvelsnap.io/images/cards/260.webp", shape: "image"});
nodes.push({id: "Slapstick", image: "https://images.marvelsnap.io/images/cards/261.webp", shape: "image"});
nodes.push({id: "Snowguard", image: "https://images.marvelsnap.io/images/cards/262.webp", shape: "image"});
nodes.push({id: "Spectrum", image: "https://images.marvelsnap.io/images/cards/115.webp", shape: "image"});
nodes.push({id: "Spider-Man", image: "https://images.marvelsnap.io/images/cards/116.webp", shape: "image"});
nodes.push({id: "Spider-Man (Miles Morales)", image: "https://images.marvelsnap.io/images/cards/264.webp", shape: "image"});
nodes.push({id: "Spider-Woman", image: "https://images.marvelsnap.io/images/cards/117.webp", shape: "image"});
nodes.push({id: "Squirrel Girl", image: "https://images.marvelsnap.io/images/cards/118.webp", shape: "image"});
nodes.push({id: "Star Lord", image: "https://images.marvelsnap.io/images/cards/119.webp", shape: "image"});
nodes.push({id: "Storm", image: "https://images.marvelsnap.io/images/cards/120.webp", shape: "image"});
nodes.push({id: "Strong Guy", image: "https://images.marvelsnap.io/images/cards/121.webp", shape: "image"});
nodes.push({id: "Stryfe", image: "https://images.marvelsnap.io/images/cards/265.webp", shape: "image"});
nodes.push({id: "Sunspot", image: "https://images.marvelsnap.io/images/cards/122.webp", shape: "image"});
nodes.push({id: "Super Skrull", image: "https://images.marvelsnap.io/images/cards/266.webp", shape: "image"});
nodes.push({id: "Surtur", image: "https://images.marvelsnap.io/images/cards/267.webp", shape: "image"});
nodes.push({id: "Swarm", image: "https://images.marvelsnap.io/images/cards/123.webp", shape: "image"});
nodes.push({id: "Sword Master", image: "https://images.marvelsnap.io/images/cards/124.webp", shape: "image"});
nodes.push({id: "Taskmaster", image: "https://images.marvelsnap.io/images/cards/125.webp", shape: "image"});
nodes.push({id: "Thanos", image: "https://images.marvelsnap.io/images/cards/126.webp", shape: "image"});
nodes.push({id: "The Collector", image: "https://images.marvelsnap.io/images/cards/127.webp", shape: "image"});
nodes.push({id: "The Hood", image: "https://images.marvelsnap.io/images/cards/128.webp", shape: "image"});
nodes.push({id: "The Infinaut", image: "https://images.marvelsnap.io/images/cards/129.webp", shape: "image"});
nodes.push({id: "The Living Tribunal", image: "https://images.marvelsnap.io/images/cards/268.webp", shape: "image"});
nodes.push({id: "The Punisher", image: "https://images.marvelsnap.io/images/cards/99.webp", shape: "image"});
nodes.push({id: "The Thing", image: "https://images.marvelsnap.io/images/cards/130.webp", shape: "image"});
nodes.push({id: "The Void", image: "https://images.marvelsnap.io/images/cards/269.webp", shape: "image"});
nodes.push({id: "Thor", image: "https://images.marvelsnap.io/images/cards/317.webp", shape: "image"});
nodes.push({id: "Titania", image: "https://images.marvelsnap.io/images/cards/271.webp", shape: "image"});
nodes.push({id: "Typhoid Mary", image: "https://images.marvelsnap.io/images/cards/131.webp", shape: "image"});
nodes.push({id: "Uatu the Watcher", image: "https://images.marvelsnap.io/images/cards/132.webp", shape: "image"});
nodes.push({id: "Ultron", image: "https://images.marvelsnap.io/images/cards/133.webp", shape: "image"});
nodes.push({id: "Uncle Ben", image: "https://images.marvelsnap.io/images/cards/272.webp", shape: "image"});
nodes.push({id: "Valkyrie", image: "https://images.marvelsnap.io/images/cards/273.webp", shape: "image"});
nodes.push({id: "Venom", image: "https://images.marvelsnap.io/images/cards/134.webp", shape: "image"});
nodes.push({id: "Viper", image: "https://images.marvelsnap.io/images/cards/135.webp", shape: "image"});
nodes.push({id: "Vision", image: "https://images.marvelsnap.io/images/cards/136.webp", shape: "image"});
nodes.push({id: "Vulture", image: "https://images.marvelsnap.io/images/cards/137.webp", shape: "image"});
nodes.push({id: "War Machine", image: "https://images.marvelsnap.io/images/cards/321.webp", shape: "image"});
nodes.push({id: "Warpath", image: "https://images.marvelsnap.io/images/cards/274.webp", shape: "image"});
nodes.push({id: "Wasp", image: "https://images.marvelsnap.io/images/cards/138.webp", shape: "image"});
nodes.push({id: "Wave", image: "https://images.marvelsnap.io/images/cards/139.webp", shape: "image"});
nodes.push({id: "White Queen", image: "https://images.marvelsnap.io/images/cards/140.webp", shape: "image"});
nodes.push({id: "White Tiger", image: "https://images.marvelsnap.io/images/cards/141.webp", shape: "image"});
nodes.push({id: "Widow's Bite", image: "https://images.marvelsnap.io/images/cards/275.webp", shape: "image"});
nodes.push({id: "Wolfsbane", image: "https://images.marvelsnap.io/images/cards/142.webp", shape: "image"});
nodes.push({id: "Wolverine", image: "https://images.marvelsnap.io/images/cards/143.webp", shape: "image"});
nodes.push({id: "Wong", image: "https://images.marvelsnap.io/images/cards/144.webp", shape: "image"});
nodes.push({id: "Yellowjacket", image: "https://images.marvelsnap.io/images/cards/145.webp", shape: "image"});
nodes.push({id: "Yo-Yo", image: "https://images.marvelsnap.io/images/cards/322.webp", shape: "image"});
nodes.push({id: "Yondu", image: "https://images.marvelsnap.io/images/cards/146.webp", shape: "image"});
nodes.push({id: "Zabu", image: "https://images.marvelsnap.io/images/cards/277.webp", shape: "image"});
nodes.push({id: "Zero", image: "https://images.marvelsnap.io/images/cards/278.webp", shape: "image"});

export default nodes
