const edges = [];

edges.push({ from: 'Absorbing Man', to: 'Apocalypse', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Absorbing Man', to: 'Blade', arrows: 'to', color: { color: 'green' } });
edges.push({
	from: 'Absorbing Man',
	to: 'Doctor Strange',
	arrows: 'to',
	color: { color: 'green' }
});
edges.push({ from: 'Absorbing Man', to: 'Galactus', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Absorbing Man', to: 'Iron Fist', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Absorbing Man', to: 'MODOK', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Absorbing Man', to: 'Spider-Man', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Absorbing Man', to: 'Sword Master', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Adam Warlock', to: 'Devil Dinosaur', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Adam Warlock', to: 'Drax', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Adam Warlock', to: 'Gamora', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Adam Warlock', to: 'Groot', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Adam Warlock', to: 'Lizard', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Adam Warlock', to: 'Mantis', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Adam Warlock', to: 'Nebula', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Adam Warlock', to: 'Rocket Racoon', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Adam Warlock', to: 'Star Lord', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Aero', to: 'Kraven', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Agent 13', to: 'Devil Dinosaur', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Agent 13', to: 'The Collector', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Agent Coulson', to: 'The Collector', arrows: 'to', color: { color: 'green' } });
edges.push({
	from: 'America Chavez',
	to: 'Agatha Harkness',
	arrows: 'to',
	color: { color: 'green' }
});
edges.push({ from: 'America Chavez', to: 'Lockjaw', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Angel', to: 'Carnage', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Angela', to: 'Bishop', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Angela', to: 'Sera', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Armor', to: 'Carnage', arrows: 'to', color: { color: 'red' } });
edges.push({ from: 'Armor', to: 'Death', arrows: 'to', color: { color: 'red' } });
edges.push({ from: 'Armor', to: 'Deathlok', arrows: 'to', color: { color: 'red' } });
edges.push({ from: 'Armor', to: 'Destroyer', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Armor', to: 'Gambit', arrows: 'to', color: { color: 'red' } });
edges.push({ from: 'Armor', to: 'Killmonger', arrows: 'to', color: { color: 'red' } });
edges.push({ from: 'Armor', to: 'Knull', arrows: 'to', color: { color: 'red' } });
edges.push({ from: 'Armor', to: 'Shang-Chi', arrows: 'to', color: { color: 'red' } });
edges.push({ from: 'Armor', to: 'Venom', arrows: 'to', color: { color: 'red' } });
edges.push({ from: 'Arnim Zola', to: 'Black Panther', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Arnim Zola', to: 'Death', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Arnim Zola', to: 'Ebony Maw', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Arnim Zola', to: 'Knull', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Arnim Zola', to: 'Mister Negative', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Arnim Zola', to: 'Red Skull', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Arnim Zola', to: 'Shuri', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Arnim Zola', to: 'Venom', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Arnim Zola', to: 'Wolverine', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Arnim Zola', to: 'Black Panther', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Baron Mordo', to: 'Ronan', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Bast', to: 'Cerebro', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Bishop', to: 'Mysterio', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Black Knight', to: 'Carnage', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Black Knight', to: 'Deathlok', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Black Knight', to: 'Venom', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Black Widow', to: 'Darkhawk', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Black Widow', to: 'The Punisher', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Blade', to: 'Apocalypse', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Blade', to: 'Hela', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Blade', to: 'Helicarrier', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Blade', to: 'Morbius', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Blade', to: 'Sabretooth', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Blade', to: 'Swarm', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Blade', to: 'Wolverine', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Bucky Barnes', to: 'Carnage', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Bucky Barnes', to: 'Deathlok', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Bucky Barnes', to: 'Venom', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Cable', to: 'Devil Dinosaur', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Cable', to: 'The Collector', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Captain Marvel', to: 'Kraven', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Carnage', to: 'Deadpool', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Carnage', to: 'Knull', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Carnage', to: 'Mister Sinister', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Carnage', to: 'Nova', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Carnage', to: 'Sabretooth', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Carnage', to: 'Wolverine', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Cerebro', to: 'Brood', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Cerebro', to: 'Goose', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Cerebro', to: 'Iceman', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Cerebro', to: 'Korg', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Cerebro', to: 'Mister Fantastic', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Cerebro', to: 'Mister Sinister', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Cerebro', to: 'Nightcrawler', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Cerebro', to: 'Sentinel', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Cloak', to: 'Kraven', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Cloak', to: 'Multiple Man', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Cloak', to: 'Vulture', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Colleen Wing', to: 'Lockjaw', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Colleen Wing', to: 'Silver Samurai', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Colleen Wing', to: 'Swarm', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Cosmo', to: 'Absorbing Man', arrows: 'to', color: { color: 'red' } });
edges.push({ from: 'Cosmo', to: 'Aero', arrows: 'to', color: { color: 'red' } });
edges.push({ from: 'Cosmo', to: 'Agent Coulson', arrows: 'to', color: { color: 'red' } });
edges.push({ from: 'Cosmo', to: 'Arnim Zola', arrows: 'to', color: { color: 'red' } });
edges.push({ from: 'Cosmo', to: 'Black Bolt', arrows: 'to', color: { color: 'red' } });
edges.push({ from: 'Cosmo', to: 'Black Panther', arrows: 'to', color: { color: 'red' } });
edges.push({ from: 'Cosmo', to: 'Carnage', arrows: 'to', color: { color: 'red' } });
edges.push({ from: 'Cosmo', to: 'Deathlok', arrows: 'to', color: { color: 'red' } });
edges.push({ from: 'Cosmo', to: 'Destroyer', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Cosmo', to: 'Doctor Doom', arrows: 'to', color: { color: 'red' } });
edges.push({ from: 'Cosmo', to: 'Doctor Octopus', arrows: 'to', color: { color: 'red' } });
edges.push({ from: 'Cosmo', to: 'Drax', arrows: 'to', color: { color: 'red' } });
edges.push({ from: 'Cosmo', to: 'Enchantress', arrows: 'to', color: { color: 'red' } });
edges.push({ from: 'Cosmo', to: 'Galactus', arrows: 'to', color: { color: 'red' } });
edges.push({ from: 'Cosmo', to: 'Gambit', arrows: 'to', color: { color: 'red' } });
edges.push({ from: 'Cosmo', to: 'Gamora', arrows: 'to', color: { color: 'red' } });
edges.push({ from: 'Cosmo', to: 'Heimdall', arrows: 'to', color: { color: 'red' } });
edges.push({ from: 'Cosmo', to: 'Hela', arrows: 'to', color: { color: 'red' } });
edges.push({ from: 'Cosmo', to: 'Hellcow', arrows: 'to', color: { color: 'red' } });
edges.push({ from: 'Cosmo', to: 'Hobgoblin', arrows: 'to', color: { color: 'red' } });
edges.push({ from: 'Cosmo', to: 'Jane foster', arrows: 'to', color: { color: 'red' } });
edges.push({ from: 'Cosmo', to: 'Jubilee', arrows: 'to', color: { color: 'red' } });
edges.push({ from: 'Cosmo', to: 'Kang', arrows: 'to', color: { color: 'red' } });
edges.push({ from: 'Cosmo', to: 'Leader', arrows: 'to', color: { color: 'red' } });
edges.push({ from: 'Cosmo', to: 'Leech', arrows: 'to', color: { color: 'red' } });
edges.push({ from: 'Cosmo', to: 'Magik', arrows: 'to', color: { color: 'red' } });
edges.push({ from: 'Cosmo', to: 'Magneto', arrows: 'to', color: { color: 'red' } });
edges.push({ from: 'Cosmo', to: 'Maximus', arrows: 'to', color: { color: 'red' } });
edges.push({ from: 'Cosmo', to: 'Mister Negative', arrows: 'to', color: { color: 'red' } });
edges.push({ from: 'Cosmo', to: 'Modok', arrows: 'to', color: { color: 'red' } });
edges.push({ from: 'Cosmo', to: 'Moon Girl', arrows: 'to', color: { color: 'red' } });
edges.push({ from: 'Cosmo', to: 'Nick Fury', arrows: 'to', color: { color: 'red' } });
edges.push({ from: 'Cosmo', to: 'Odin', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Cosmo', to: 'Rescue', arrows: 'to', color: { color: 'red' } });
edges.push({ from: 'Cosmo', to: 'Rockslide', arrows: 'to', color: { color: 'red' } });
edges.push({ from: 'Cosmo', to: 'Sentry', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Cosmo', to: 'Shuri', arrows: 'to', color: { color: 'red' } });
edges.push({ from: 'Cosmo', to: 'Silver Surfer', arrows: 'to', color: { color: 'red' } });
edges.push({ from: 'Cosmo', to: 'Spectrum', arrows: 'to', color: { color: 'red' } });
edges.push({ from: 'Cosmo', to: 'Spider-Man', arrows: 'to', color: { color: 'red' } });
edges.push({ from: 'Cosmo', to: 'Spider-Woman', arrows: 'to', color: { color: 'red' } });
edges.push({ from: 'Cosmo', to: 'Taskmaster', arrows: 'to', color: { color: 'red' } });
edges.push({ from: 'Cosmo', to: 'Thor', arrows: 'to', color: { color: 'red' } });
edges.push({ from: 'Cosmo', to: 'Ultron', arrows: 'to', color: { color: 'red' } });
edges.push({ from: 'Cosmo', to: 'Valkyrie', arrows: 'to', color: { color: 'red' } });
edges.push({ from: 'Cosmo', to: 'Venom', arrows: 'to', color: { color: 'red' } });
edges.push({ from: 'Cosmo', to: 'White Tiger', arrows: 'to', color: { color: 'red' } });
edges.push({ from: 'Cosmo', to: 'Wong', arrows: 'to', color: { color: 'red' } });
edges.push({ from: 'Dagger', to: 'Doctor Strange', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Dagger', to: 'Heimdall', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Dagger', to: 'Iron Fist', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Dagger', to: 'Kraven', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Daredevil', to: 'Aero', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Daredevil', to: 'Galactus', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Daredevil', to: 'Professor X', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Daredevil', to: 'Spider-Man', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Deadpool', to: 'Death', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Deadpool', to: 'Knull', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Deathlok', to: 'Deadpool', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Deathlok', to: 'Knull', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Deathlok', to: 'Sabretooth', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Deathlok', to: 'Wolverine', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Debrii', to: 'Carnage', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Debrii', to: 'Kazar', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Debrii', to: 'Wong', arrows: 'to', color: { color: 'red' } });
edges.push({ from: 'Destroyer', to: 'Death', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Destroyer', to: 'Knull', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Doctor Doom', to: 'Professor X', arrows: 'to', color: { color: 'red' } });
edges.push({ from: 'Doctor Strange', to: 'Ebony Maw', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Doctor Strange', to: 'Human Torch', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Doctor Strange', to: 'Kraven', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Doctor Strange', to: 'Multiple Man', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Doctor Strange', to: 'Vulture', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Domino', to: 'Agatha Harkness', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Dracula', to: 'Apocalypse', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Dracula', to: 'Blade', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Dracula', to: 'Infinaut', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Dracula', to: 'Lady Sif', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Dracula', to: 'Sword Master', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Elektra', to: 'Sunspot', arrows: 'to', color: { color: 'red' } });
edges.push({ from: 'Enchantress', to: 'Armor', arrows: 'to', color: { color: 'red' } });
edges.push({ from: 'Enchantress', to: 'Blob', arrows: 'to', color: { color: 'red' } });
edges.push({ from: 'Enchantress', to: 'Blue Marvel', arrows: 'to', color: { color: 'red' } });
edges.push({ from: 'Enchantress', to: 'Captain America', arrows: 'to', color: { color: 'red' } });
edges.push({ from: 'Enchantress', to: 'Cerebro', arrows: 'to', color: { color: 'red' } });
edges.push({ from: 'Enchantress', to: 'Colossus', arrows: 'to', color: { color: 'red' } });
edges.push({ from: 'Enchantress', to: 'Dazzler', arrows: 'to', color: { color: 'red' } });
edges.push({ from: 'Enchantress', to: 'Devil Dino', arrows: 'to', color: { color: 'red' } });
edges.push({ from: 'Enchantress', to: 'Ebony Maw', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Enchantress', to: 'Electro', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Enchantress', to: 'Invisible Woman', arrows: 'to', color: { color: 'red' } });
edges.push({ from: 'Enchantress', to: 'Iron Man', arrows: 'to', color: { color: 'red' } });
edges.push({ from: 'Enchantress', to: 'Kazar', arrows: 'to', color: { color: 'red' } });
edges.push({ from: 'Enchantress', to: 'Klaw', arrows: 'to', color: { color: 'red' } });
edges.push({ from: 'Enchantress', to: 'Lizard', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Enchantress', to: 'Luke Cage', arrows: 'to', color: { color: 'red' } });
edges.push({ from: 'Enchantress', to: 'Mister Fantastic', arrows: 'to', color: { color: 'red' } });
edges.push({ from: 'Enchantress', to: 'Mojo', arrows: 'to', color: { color: 'red' } });
edges.push({ from: 'Enchantress', to: 'Morbius', arrows: 'to', color: { color: 'red' } });
edges.push({ from: 'Enchantress', to: 'Ms Marvel', arrows: 'to', color: { color: 'red' } });
edges.push({ from: 'Enchantress', to: 'Mystique', arrows: 'to', color: { color: 'red' } });
edges.push({ from: 'Enchantress', to: 'Namor', arrows: 'to', color: { color: 'red' } });
edges.push({ from: 'Enchantress', to: 'Omega Red', arrows: 'to', color: { color: 'red' } });
edges.push({ from: 'Enchantress', to: 'Onslaught', arrows: 'to', color: { color: 'red' } });
edges.push({ from: 'Enchantress', to: 'Orka', arrows: 'to', color: { color: 'red' } });
edges.push({ from: 'Enchantress', to: 'Patriot', arrows: 'to', color: { color: 'red' } });
edges.push({ from: 'Enchantress', to: 'Punisher', arrows: 'to', color: { color: 'red' } });
edges.push({ from: 'Enchantress', to: 'Quinjet', arrows: 'to', color: { color: 'red' } });
edges.push({ from: 'Enchantress', to: 'Red Skull', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Enchantress', to: 'Rogue', arrows: 'to', color: { color: 'red' } });
edges.push({ from: 'Enchantress', to: 'Ronan', arrows: 'to', color: { color: 'red' } });
edges.push({ from: 'Enchantress', to: 'Sandman', arrows: 'to', color: { color: 'red' } });
edges.push({ from: 'Enchantress', to: 'Sauron', arrows: 'to', color: { color: 'red' } });
edges.push({ from: 'Enchantress', to: 'Strong Guy', arrows: 'to', color: { color: 'red' } });
edges.push({ from: 'Enchantress', to: 'Super Skrull', arrows: 'to', color: { color: 'red' } });
edges.push({ from: 'Enchantress', to: 'Typhoid Mary', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Enchantress', to: 'Warpath', arrows: 'to', color: { color: 'red' } });
edges.push({ from: 'Enchantress', to: 'Wong', arrows: 'to', color: { color: 'red' } });
edges.push({ from: 'Enchantress', to: 'Zabu', arrows: 'to', color: { color: 'red' } });
edges.push({ from: 'Falcon', to: 'Killmonger', arrows: 'to', color: { color: 'red' } });
edges.push({ from: 'Forge', to: 'Black Panther', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Forge', to: 'Deadpool', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Forge', to: 'Human Torch', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Forge', to: 'Odin', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Forge', to: 'Shuri', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Forge', to: 'Wong', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Galactus', to: 'Deadpool', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Galactus', to: 'Knull', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Galactus', to: 'Wolverine', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Gambit', to: 'Apocalypse', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Gambit', to: 'Death', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Gambit', to: 'Knull', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Gambit', to: 'Mystique', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Gambit', to: 'Swarm', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Gambit', to: 'Wolverine', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Gambit', to: 'Wong', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Ghost Rider', to: 'Blade', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Ghost Rider', to: 'Lady Sif', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Ghost Rider', to: 'Sword Master', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Ghost rider', to: 'Moon Knight', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Ghost', to: 'Modok', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Ghost-Spider', to: 'Human Torch', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Ghost-Spider', to: 'Iron Fist', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Ghost-Spider', to: 'Kraven', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Ghost-Spider', to: 'Multiple Man', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Ghost-Spider', to: 'Nightcrawler', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Ghost-Spider', to: 'Vulture', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Goose', to: 'Enchantress', arrows: 'to', color: { color: 'red' } });
edges.push({ from: 'Goose', to: 'Maximus', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Goose', to: 'Storm', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Green Goblin', to: 'Orka', arrows: 'to', color: { color: 'red' } });
edges.push({ from: 'Green Goblin', to: 'Warpath', arrows: 'to', color: { color: 'red' } });
edges.push({ from: 'Heimdall', to: 'Ebony Maw', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Heimdall', to: 'Human Torch', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Heimdall', to: 'Kraven', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Heimdall', to: 'Vulture', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Hela', to: 'Helicarrier', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Hela', to: 'Helicarrier', arrows: 'to', color: { color: 'red' } });
edges.push({ from: 'Hellcow', to: 'Apocalypse', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Hellcow', to: 'Helicarrier', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Hellcow', to: 'Morbius', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Hellcow', to: 'Sabretooth', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Hellcow', to: 'Silver Samurai', arrows: 'to', color: { color: 'yellow' } });
edges.push({ from: 'Hellcow', to: 'Swarm', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Hellcow', to: 'Wolverine', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Hobgoblin', to: 'Lizard', arrows: 'to', color: { color: 'yellow' } });
edges.push({ from: 'Hobgoblin', to: 'Namor', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Hobgoblin', to: 'Namor', arrows: 'to', color: { color: 'red' } });
edges.push({ from: 'Hobgoblin', to: 'Orka', arrows: 'to', color: { color: 'red' } });
edges.push({ from: 'Hobgoblin', to: 'The Punisher', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Hobgoblin', to: 'Warpath', arrows: 'to', color: { color: 'red' } });
edges.push({ from: 'Hulk Buster', to: 'Deadpool', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Hulk Buster', to: 'Human Torch', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Hulk Buster', to: 'Multiple Man', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Hulk Buster', to: 'Nightcrawler', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Hulk Buster', to: 'Vulture', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Hulk', to: 'Patriot', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Iceman', to: 'Sera', arrows: 'to', color: { color: 'red' } });
edges.push({ from: 'Infinaut', to: 'lockjaw', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Invisible Woman', to: 'Hela', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Invisible Woman', to: 'Modok', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Iron Fist', to: 'Human Torch', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Iron Fist', to: 'Kraven', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Iron Fist', to: 'Multiple Man', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Ironheart', to: 'Multiple Man', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Jane foster', to: 'Lockjaw', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Jean Grey', to: 'Drax', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Jean Grey', to: 'Groot', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Jean Grey', to: 'Rocket Racoon', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Jean Grey', to: 'Star Lord', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Jubilee', to: 'Giganto', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Kazar', to: 'Squirrel Girl', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Killmonger', to: 'Agent 13', arrows: 'to', color: { color: 'red' } });
edges.push({ from: 'Killmonger', to: 'Angel', arrows: 'to', color: { color: 'red' } });
edges.push({ from: 'Killmonger', to: 'Ant-Man', arrows: 'to', color: { color: 'red' } });
edges.push({ from: 'Killmonger', to: 'Bast', arrows: 'to', color: { color: 'red' } });
edges.push({ from: 'Killmonger', to: 'Black Knight', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Killmonger', to: 'Blade', arrows: 'to', color: { color: 'red' } });
edges.push({ from: 'Killmonger', to: 'Bullseye', arrows: 'to', color: { color: 'red' } });
edges.push({ from: 'Killmonger', to: 'Deadpool', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Killmonger', to: 'Death', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Killmonger', to: 'Ebony Maw', arrows: 'to', color: { color: 'red' } });
edges.push({ from: 'Killmonger', to: 'Elektra', arrows: 'to', color: { color: 'red' } });
edges.push({ from: 'Killmonger', to: 'Elsa Bloodstone', arrows: 'to', color: { color: 'red' } });
edges.push({ from: 'Killmonger', to: 'Ghost', arrows: 'to', color: { color: 'red' } });
edges.push({ from: 'Killmonger', to: 'Hawkeye', arrows: 'to', color: { color: 'red' } });
edges.push({ from: 'Killmonger', to: 'Human Torch', arrows: 'to', color: { color: 'red' } });
edges.push({ from: 'Killmonger', to: 'Iceman', arrows: 'to', color: { color: 'red' } });
edges.push({ from: 'Killmonger', to: 'Iron Fist', arrows: 'to', color: { color: 'red' } });
edges.push({ from: 'Killmonger', to: 'Kazar', arrows: 'to', color: { color: 'red' } });
edges.push({ from: 'Killmonger', to: 'Kitty Pryde', arrows: 'to', color: { color: 'red' } });
edges.push({ from: 'Killmonger', to: 'Knull', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Killmonger', to: 'Korg', arrows: 'to', color: { color: 'red' } });
edges.push({ from: 'Killmonger', to: 'Mantis', arrows: 'to', color: { color: 'red' } });
edges.push({ from: 'Killmonger', to: 'Misty Knight', arrows: 'to', color: { color: 'red' } });
edges.push({ from: 'Killmonger', to: 'Nebula', arrows: 'to', color: { color: 'red' } });
edges.push({ from: 'Killmonger', to: 'Nightcrawler', arrows: 'to', color: { color: 'red' } });
edges.push({ from: 'Killmonger', to: 'Nova', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Killmonger', to: 'Quicksilver', arrows: 'to', color: { color: 'red' } });
edges.push({ from: 'Killmonger', to: 'Quinjet', arrows: 'to', color: { color: 'red' } });
edges.push({ from: 'Killmonger', to: 'Rocket Racoon', arrows: 'to', color: { color: 'yellow' } });
edges.push({
	from: 'Killmonger',
	to: 'Shanna the She-Devil',
	arrows: 'to',
	color: { color: 'red' }
});
edges.push({ from: 'Killmonger', to: 'Silver Samurai', arrows: 'to', color: { color: 'red' } });
edges.push({ from: 'Killmonger', to: 'Squirrel Girl', arrows: 'to', color: { color: 'red' } });
edges.push({ from: 'Killmonger', to: 'Sunspot', arrows: 'to', color: { color: 'red' } });
edges.push({ from: 'Killmonger', to: 'The Hood', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Killmonger', to: 'Titania', arrows: 'to', color: { color: 'red' } });
edges.push({ from: 'Killmonger', to: 'Uatu', arrows: 'to', color: { color: 'red' } });
edges.push({ from: 'Killmonger', to: 'Uncle Ben', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Killmonger', to: 'Yondu', arrows: 'to', color: { color: 'red' } });
edges.push({ from: 'Killmonger', to: 'Zero', arrows: 'to', color: { color: 'red' } });
edges.push({ from: 'Kingpin', to: 'Captain Marvel', arrows: 'to', color: { color: 'red' } });
edges.push({ from: 'Kingpin', to: 'Doctor Strange', arrows: 'to', color: { color: 'red' } });
edges.push({ from: 'Kingpin', to: 'Heimdall', arrows: 'to', color: { color: 'red' } });
edges.push({ from: 'Kingpin', to: 'Nightcrawler', arrows: 'to', color: { color: 'red' } });
edges.push({ from: 'Kingpin', to: 'Vision', arrows: 'to', color: { color: 'red' } });
edges.push({ from: 'Kitty Pryde', to: 'Angela', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Korg', to: 'Darkhawk', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Korg', to: 'Yondu', arrows: 'to', color: { color: 'yellow' } });
edges.push({ from: 'Lady Sif', to: 'Apocalypse', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Lady Sif', to: 'Hela', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Lady Sif', to: 'Morbius', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Lady Sif', to: 'Swarm', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Lady Sif', to: 'Wolverine', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Leech', to: 'sunspot', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Lockjaw', to: 'Dracula', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Lockjaw', to: 'Infinaut', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Lockjaw', to: 'Lady sif', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Lockjaw', to: 'Thor', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Lockjaw', to: 'Vision', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Luke Cage', to: 'Cerebro', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Luke Cage', to: 'Hazmat', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Luke Cage', to: 'Typhoid Mary', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'MODOK', to: 'Apocalypse', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'MODOK', to: 'Hela', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'MODOK', to: 'Morbius', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'MODOK', to: 'Swarm', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'MODOK', to: 'Wolverine', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Magneto', to: 'Kraven', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Mantis', to: 'Collector', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Mantis', to: 'Devil Dino', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Maria Hill', to: 'Devil dino', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Maximus', to: 'Darkhawk', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Maximus', to: 'Dracula', arrows: 'to', color: { color: 'red' } });
edges.push({ from: 'Maximus', to: 'Ronan', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Maximus', to: 'Sera', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Miles Morales', to: 'Cloak', arrows: 'to', color: { color: 'green' } });
edges.push({
	from: 'Miles Morales',
	to: 'Doctor Strange',
	arrows: 'to',
	color: { color: 'green' }
});
edges.push({ from: 'Miles Morales', to: 'Heimdall', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Miles Morales', to: 'Iron Fist', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Miles Morales', to: 'Kraven', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Mister Negative', to: 'Ironheart', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Mister Negative', to: 'Mephisto', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Mister Negative', to: 'Morph', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Mister Negative', to: 'Mystique', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Mister Negative', to: 'Taskmaster', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Modok', to: 'Helicarrier', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Modok', to: 'Morbius', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Moon Girl', to: 'Devil Dinosaur', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Moon Girl', to: 'Spider-Man', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Moon Girl', to: 'The Collector', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Moon Knight', to: 'Apocalypse', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Moon Knight', to: 'Hela', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Moon Knight', to: 'Helicarrier', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Moon Knight', to: 'Morbius', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Moon Knight', to: 'Sabretooth', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Moon Knight', to: 'Swarm', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Moon Knight', to: 'Wolverine', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Multiple Man', to: 'Hulk Buster', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Multiple Man', to: 'Ironheart', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Mysterio', to: 'Angela', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Mysterio', to: 'Bishop', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Mysterio', to: 'Carnage', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Mystique', to: 'Armor', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Mystique', to: 'Blob', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Mystique', to: 'Blue Marvel', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Mystique', to: 'Captain America', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Mystique', to: 'Cerebro', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Mystique', to: 'Cosmo', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Mystique', to: 'Devil Dinosaur', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Mystique', to: 'Ebony Maw', arrows: 'to', color: { color: 'yellow' } });
edges.push({ from: 'Mystique', to: 'Enchantress', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Mystique', to: 'Iron Man', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Mystique', to: 'Kazar', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Mystique', to: 'Klaw', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Mystique', to: 'Lizard', arrows: 'to', color: { color: 'yellow' } });
edges.push({ from: 'Mystique', to: 'Mister Fantastic', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Mystique', to: 'Omega Red', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Mystique', to: 'Patriot', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Mystique', to: 'Professor X', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Mystique', to: 'Quinjet', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Mystique', to: 'Ronan', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Mystique', to: 'Super Skrull', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Mystique', to: 'The Punisher', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Mystique', to: 'Wong', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Mystique', to: 'Zabu', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Nakia', to: 'Black Panther', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Nakia', to: 'Brood', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Nakia', to: 'Hobgoblin', arrows: 'to', color: { color: 'yellow' } });
edges.push({ from: 'Nakia', to: 'Mister Sinister', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Nick Fury', to: 'Devil Dinosaur', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Nick Fury', to: 'The Collector', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Nightcrawler', to: 'Ebony Maw', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Nightcrawler', to: 'Kraven', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Nova', to: 'Squirrel Girl', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Odin', to: 'Gambit', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Odin', to: 'Ironheart', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Odin', to: 'White Tiger', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Odin', to: 'Wong', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Okoye', to: 'Black Panther', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Okoye', to: 'Brood', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Okoye', to: 'Deadpool', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Okoye', to: 'Human Torch', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Okoye', to: 'Mister Sinister', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Onslaught', to: 'Blue Marvel', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Onslaught', to: 'Captain America', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Onslaught', to: 'Iron Man', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Onslaught', to: 'Kazar', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Onslaught', to: 'Klaw', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Onslaught', to: 'Mister Fantastic', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Onslaught', to: 'Mojo', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Onslaught', to: 'Mystique', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Onslaught', to: 'Omega Red', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Onslaught', to: 'Patriot', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Onslaught', to: 'Quinjet', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Onslaught', to: 'Rogue', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Onslaught', to: 'Ronan', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Onslaught', to: 'Sera', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Onslaught', to: 'Strong Guy', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Onslaught', to: 'Super Skrull', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Onslaught', to: 'The Punisher', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Patriot', to: 'Abomination', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Patriot', to: 'Cyclops', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Patriot', to: 'Debrii', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Patriot', to: 'Doctor Doom', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Patriot', to: 'Hulk', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Patriot', to: 'Mister Sinister', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Patriot', to: 'Misty Knight', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Patriot', to: 'Mysterio', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Patriot', to: 'Shocker', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Patriot', to: 'Squirrel Girl', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Patriot', to: 'The Thing', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Patriot', to: 'Ultron', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Polaris', to: 'Kraven', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Professor X', to: 'Green Goblin', arrows: 'to', color: { color: 'red' } });
edges.push({ from: 'Professor X', to: 'Hobgoblin', arrows: 'to', color: { color: 'red' } });
edges.push({ from: 'Psylocke', to: 'Mister Negative', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Quicksilver', to: 'Agatha Harkness', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Quinjet', to: 'Agent 13', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Quinjet', to: 'Agent Coulson', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Quinjet', to: 'Collector', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Quinjet', to: 'Helicarrier', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Quinjet', to: 'Maria Hill', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Quinjet', to: 'Nick Fury', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Quinjet', to: 'Thanos', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Quinjet', to: 'White Queen', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Rescue', to: 'Hulk buster', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Rescue', to: 'Jessica Jones', arrows: 'to', color: { color: 'yellow' } });
edges.push({ from: 'Rhino', to: 'Cerebro', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Rockslide', to: 'Darkhawk', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Rockslide', to: 'Yondu', arrows: 'to', color: { color: 'yellow' } });
edges.push({ from: 'Rogue', to: 'Blue Marvel', arrows: 'to', color: { color: 'red' } });
edges.push({ from: 'Rogue', to: 'Captain America', arrows: 'to', color: { color: 'red' } });
edges.push({ from: 'Rogue', to: 'Cerebro', arrows: 'to', color: { color: 'red' } });
edges.push({ from: 'Rogue', to: 'Colossus', arrows: 'to', color: { color: 'red' } });
edges.push({ from: 'Rogue', to: 'Devil Dinosaur', arrows: 'to', color: { color: 'red' } });
edges.push({ from: 'Rogue', to: 'Iron Man', arrows: 'to', color: { color: 'red' } });
edges.push({ from: 'Rogue', to: 'Kazar', arrows: 'to', color: { color: 'red' } });
edges.push({ from: 'Rogue', to: 'Klaw', arrows: 'to', color: { color: 'red' } });
edges.push({ from: 'Rogue', to: 'Luke Cage', arrows: 'to', color: { color: 'red' } });
edges.push({ from: 'Rogue', to: 'Mister Fantastic', arrows: 'to', color: { color: 'red' } });
edges.push({ from: 'Rogue', to: 'Morbius', arrows: 'to', color: { color: 'red' } });
edges.push({ from: 'Rogue', to: 'Mystique', arrows: 'to', color: { color: 'red' } });
edges.push({ from: 'Rogue', to: 'Omega Red', arrows: 'to', color: { color: 'red' } });
edges.push({ from: 'Rogue', to: 'Onslaught', arrows: 'to', color: { color: 'red' } });
edges.push({ from: 'Rogue', to: 'Patriot', arrows: 'to', color: { color: 'red' } });
edges.push({ from: 'Rogue', to: 'Quinjet', arrows: 'to', color: { color: 'red' } });
edges.push({ from: 'Rogue', to: 'Ronan', arrows: 'to', color: { color: 'red' } });
edges.push({ from: 'Rogue', to: 'Super Skrull', arrows: 'to', color: { color: 'red' } });
edges.push({ from: 'Rogue', to: 'Wong', arrows: 'to', color: { color: 'red' } });
edges.push({ from: 'Rogue', to: 'Zabu', arrows: 'to', color: { color: 'red' } });
edges.push({ from: 'Sabretooth', to: 'Bishop', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Sabretooth', to: 'Death', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Sabretooth', to: 'Hit Monkey', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Sabretooth', to: 'Knull', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Sabretooth', to: 'The Collector', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Sauron', to: 'Lizard', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Sauron', to: 'Zero', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Scorpion', to: 'Black Panther', arrows: 'to', color: { color: 'red' } });
edges.push({ from: 'Scorpion', to: 'Cerebro', arrows: 'to', color: { color: 'red' } });
edges.push({ from: 'Scorpion', to: 'Deadpool', arrows: 'to', color: { color: 'red' } });
edges.push({ from: 'Scorpion', to: 'Human Torch', arrows: 'to', color: { color: 'red' } });
edges.push({ from: 'Sentinel', to: 'Devil dino', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Sentry', to: 'Carnage', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Sentry', to: 'Viper', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Sera', to: 'Brood', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Sera', to: 'Hit Monkey', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Sera', to: 'Killmonger', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Sera', to: 'Maximus', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Sera', to: 'Silver Surfer', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Sera', to: 'Wong', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Sera', to: 'Zabu', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Shadow King', to: 'Black Panther', arrows: 'to', color: { color: 'red' } });
edges.push({ from: 'Shadow King', to: 'Nova', arrows: 'to', color: { color: 'red' } });
edges.push({ from: 'Shadow King', to: 'Shuri', arrows: 'to', color: { color: 'red' } });
edges.push({ from: 'Shadow King', to: 'Silver Surfer', arrows: 'to', color: { color: 'red' } });
edges.push({ from: 'Shadow King', to: 'Venom', arrows: 'to', color: { color: 'red' } });
edges.push({ from: 'Shang-Chi', to: 'Death', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'She-Hulk', to: 'Infinaut', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'She-Hulk', to: 'Sunspot', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Shuri', to: 'Captain Marvel', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Shuri', to: 'Deadpool', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Shuri', to: 'Infinaut', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Shuri', to: 'Red Skull', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Shuri', to: 'Vision', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Silver Samurai', to: 'Blade', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Silver Surfer', to: 'Bishop', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Silver Surfer', to: 'Brood', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Silver Surfer', to: 'Cosmo', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Silver Surfer', to: 'Debrii', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Silver Surfer', to: 'Green Goblin', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Silver Surfer', to: 'Groot', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Silver Surfer', to: 'Ironheart', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Silver Surfer', to: 'Juggernaut', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Silver Surfer', to: 'Maximus', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Silver Surfer', to: 'Mystique', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Silver Surfer', to: 'Patriot', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Silver Surfer', to: 'Rhino', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Spectrum', to: 'Armor', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Spectrum', to: 'Blob', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Spectrum', to: 'Blue Marvel', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Spectrum', to: 'Captain America', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Spectrum', to: 'Colossus', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Spectrum', to: 'Cosmo', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Spectrum', to: 'Dazzler', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Spectrum', to: 'Devil Dino', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Spectrum', to: 'Ebony Maw', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Spectrum', to: 'Electro', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Spectrum', to: 'Enchantress', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Spectrum', to: 'Goose', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Spectrum', to: 'Invisible Woman', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Spectrum', to: 'Iron Man', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Spectrum', to: 'Kazar', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Spectrum', to: 'Klaw', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Spectrum', to: 'Lizard', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Spectrum', to: 'Luke Cage', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Spectrum', to: 'Mister Fantastic', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Spectrum', to: 'Mojo', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Spectrum', to: 'Morbius', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Spectrum', to: 'Ms Marvel', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Spectrum', to: 'Mystique', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Spectrum', to: 'Namor', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Spectrum', to: 'Omega Red', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Spectrum', to: 'Patriot', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Spectrum', to: 'Professor X', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Spectrum', to: 'Punisher', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Spectrum', to: 'Quinjet', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Spectrum', to: 'Red Skull', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Spectrum', to: 'Rogue', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Spectrum', to: 'Ronan', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Spectrum', to: 'Sandman', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Spectrum', to: 'Sauron', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Spectrum', to: 'Sera', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Spectrum', to: 'Strong Guy', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Spectrum', to: 'Super Skrull', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Spectrum', to: 'Typhoid Mary', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Spectrum', to: 'War Machine', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Spectrum', to: 'Warpath', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Spectrum', to: 'Wong', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Spectrum', to: 'Zabu', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Squirrel Girl', to: 'Carnage', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Squirrel Girl', to: 'Death', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Storm', to: 'Cerebro', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Storm', to: 'Juggernaut', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Storm', to: 'Silver Surfer', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Strong Guy', to: 'Blade', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Strong Guy', to: 'Hellcow', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Strong Guy', to: 'MODOK', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Strong Guy', to: 'Ronan', arrows: 'to', color: { color: 'red' } });
edges.push({ from: 'Strong Guy', to: 'Sword Master', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Surtur', to: 'Human Torch', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Swarm', to: 'Bishop', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Swarm', to: 'Devil Dinosaur', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Swarm', to: 'Hit Monkey', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Swarm', to: 'Lockjaw', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Sword Master', to: 'Apocalypse', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Sword Master', to: 'Hela', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Sword Master', to: 'Helicarrier', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Sword Master', to: 'Morbius', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Sword Master', to: 'Sabretooth', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Sword Master', to: 'Silver Samurai', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Sword Master', to: 'Swarm', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Sword Master', to: 'Wolverine', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Taskmaster', to: 'Mister Negative', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Taskmaster', to: 'Red Skull', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Taskmaster', to: 'She-Hulk', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Taskmaster', to: 'Shuri', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'The Collector', to: 'White Queen', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'The Hood', to: 'Carnage', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'The Hood', to: 'Deathlok', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'The Infinaut', to: 'Jessica Jones', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'The Infinaut', to: 'Sunspot', arrows: 'to', color: { color: 'green' } });
edges.push({
	from: 'Thor',
	to: 'Jane Foster Mighty Thor',
	arrows: 'to',
	color: { color: 'green' }
});
edges.push({ from: 'Thor', to: 'Lockjaw', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Typhoid Mary', to: 'Super Skrull', arrows: 'to', color: { color: 'red' } });
edges.push({ from: 'Uatu', to: 'Cerebro', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Ultron', to: 'Dazzler', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Uncle Ben', to: 'Carnage', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Valkyrie', to: 'Cerebro', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Valkyrie', to: 'Galactus', arrows: 'to', color: { color: 'red' } });
edges.push({ from: 'Venom', to: 'Deadpool', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Venom', to: 'Sabretooth', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Viper', to: 'Green Goblin', arrows: 'to', color: { color: 'red' } });
edges.push({ from: 'Viper', to: 'Hobgoblin', arrows: 'to', color: { color: 'red' } });
edges.push({ from: 'Viper', to: 'The Hood', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Vision', to: 'Kraven', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Wasp', to: 'Lockjaw', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Wave', to: 'Death', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Wave', to: 'Electro', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Wave', to: 'Galactus', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Wave', to: 'Kazar', arrows: 'to', color: { color: 'red' } });
edges.push({ from: 'Wave', to: 'Shuri', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'White Queen', to: 'Devil Dinosaur', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Wolfsbane', to: 'Ant-Man', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Wolfsbane', to: 'Brood', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Wolfsbane', to: 'Odin', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Wolfsbane', to: 'Wong', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Wolverine', to: 'Gambit', arrows: 'to', color: { color: 'red' } });
edges.push({ from: 'Wong', to: 'Black Panther', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Wong', to: 'Ironheart', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Wong', to: 'Shuri', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Wong', to: 'White Tiger', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Yellowjacket', to: 'Cosmo', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Yellowjacket', to: 'Lockjaw', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Yondu', to: 'Darkhawk', arrows: 'to', color: { color: 'red' } });
edges.push({ from: 'Yondu', to: 'Death', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Zabu', to: 'Absorbing Man', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Zabu', to: 'Attuma', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Zabu', to: 'Bishop', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Zabu', to: 'Crossbones', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Zabu', to: 'Crystal', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Zabu', to: 'Darkhawk', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Zabu', to: 'Dazzler', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Zabu', to: 'Dracula', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Zabu', to: 'Drax', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Zabu', to: 'Enchantress', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Zabu', to: 'Ghost Rider', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Zabu', to: 'Hellcow', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Zabu', to: 'Hit Monkey', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Zabu', to: 'Jessica Jones', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Zabu', to: 'Jubilee', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Zabu', to: 'Kazar', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Zabu', to: 'Mirage', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Zabu', to: 'Mister Negative', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Zabu', to: 'Moon Girl', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Zabu', to: 'Omega Red', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Zabu', to: 'Rescue', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Zabu', to: 'Rockslide', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Zabu', to: 'Sentry', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Zabu', to: 'Shadow King', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Zabu', to: 'Shang-Chi', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Zabu', to: 'Shanna', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Zabu', to: 'Shuri', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Zabu', to: 'Spider-Man', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Zabu', to: 'Super Skrull', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Zabu', to: 'White Queen', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Zabu', to: 'Wong', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Zero', to: 'Lizard', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Zero', to: 'Red Skull', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'Zero', to: 'Typhoid Mary', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'armor', to: 'zero', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'carnage', to: 'death', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'mister negative', to: 'iron man', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'moon girl', to: 'devil dinosaur', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'mystique', to: 'cerebro', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'mystique', to: 'wong', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'patriot', to: 'shocker', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'silver surfer', to: 'brood', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'sunspot', to: 'she-hulk', arrows: 'to', color: { color: 'green' } });
edges.push({ from: 'zabu', to: 'Shang-Chi', arrows: 'to', color: { color: 'green' } });

export default edges;
